### ISSUE TITLE
Installation WOGWT

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gino1234/wogwt#3]
```
What steps will reproduce the problem?
1. WO 5.3.3 + Wonder53 + WOGWT 0.5 on eclipse 3.7 (indigo) 
2. Follow getting started


What is the expected output? What do you see instead?
Test Application does not start 

What version of the product are you using? On what operating system?
Windows XP

Please provide any additional information below.

Config : add SDK (use Google Web Toolkit)  +
war directory is WebServerResources + add WOGWT.framework in build

First problem :  2 times gwt-dev.jar and wgt-user.jar
many warning :
Loading inherited module 'com.google.gwt.widgetideas.BasicTable'
Module 'com.google.gwt.widgetideas.BasicTable' has already been loaded and will 
be skipped
....
2) I dont have any tomcat directory. Image of my project attached
who is supposed to generate this ?

3) running myapp_GWTDevMod.launch finish like this
      Public resources found in...
         Refreshing resources
      Translatable source found in...
         Refreshing resources
      Bootstrap link for command-line module 'your.app.gwt.Development'
         Linking module 'your.app.gwt.Application'
            Invoking Linker RPC policy file manifest
            Invoking Linker Standard
            Invoking Linker Export CompilationResult symbol maps
            Invoking Linker Emit compile report artifacts
            Linking compilation into F:\Apple533\eclipse\workspace\TestWOGWT\WebServerResources\your.app.gwt.Application 


No url is displayed

What I am doing wrong ?

Thanks in advance
```

Original issue reported on code.google.com by `pierregi...@gmail.com` on 23 Aug 2011 at 8:28

Attachments:
- [wogwt.PNG](https://storage.googleapis.com/google-code-attachments/wogwt/issue-3/comment-0/wogwt.PNG)

**Comment by GoogleCodeExporter** [comment]
```
Having both SDKs on the build path is ok and normal.
The warnings are also normal (they are from the gwt-incubator.jar which has 
some updated things)
The startup output is also normal.  Open the Development Mode view in Eclipse 
to see the url to use.  The url will be like this:
http://localhost:8888/YourApp/WebObjects/YourApp.woa
```

Original comment by `johnth...@gmail.com` on 24 Aug 2011 at 8:27

**Comment by GoogleCodeExporter** [comment]
```
Thanks for your answer.

When I start myapp_GWTDevMod.launch,  I have "errors in required  project"
but I no help to find them.
I proceed but no url is available...

I have tryed "reload web server" in Development Mode view and then I have
the error :
   [WARN] failed woServlet
java.lang.NoClassDefFoundError: com/webobjects/jspservlet/WOServletAdaptor
    at java.lang.ClassLoader.defineClass1(Native Method)

Seems strange as I have this in my web.xml :
<servlet>
   <servlet-name>woServlet</servlet-name>
   <servlet-class>er.extensions.jspservlet.ERXServletAdaptor</servlet-class>
</servlet>

Any idea ?
```

Original comment by `pierregi...@gmail.com` on 26 Aug 2011 at 10:30

**Comment by GoogleCodeExporter** [comment]
```
Ah, that's helpful.  You need to add the JavaWOJSPServlet framework to your 
project.
```

Original comment by `johnth...@gmail.com` on 26 Aug 2011 at 12:55

**Comment by GoogleCodeExporter** [comment]
```
It is in the "Java Build Path". Do you mean that it has to be added
somewhere else ?
```

Original comment by `pierregi...@gmail.com` on 26 Aug 2011 at 2:24

**Comment by GoogleCodeExporter** [comment]
```
Here, I've attached a template app to look at.  I'm not sure what problem 
you're having but maybe this will help.

```

Original comment by `johnth...@gmail.com` on 29 Aug 2011 at 3:36

Attachments:
- [GwtExampleApp.zip](https://storage.googleapis.com/google-code-attachments/wogwt/issue-3/comment-5/GwtExampleApp.zip)

**Comment by GoogleCodeExporter** [comment]
```
Thanks John for your help,
I used your app as a start. It's help as I am now able to compile the GWT 
(permutations are genered in WebServerResources). ant build.xml generate 
correctly the WO part.
But the project is still flag with an "A and 2 red dot" (see image attached).
When running GwtExampleApp.launch, I still have "errors in required  project" 
warning and then the error :
Variable references non-existent resource :
 ${workspace_loc:StylewareCheckIn/build}

I dont know what is the problem and where to fix it...
Many thanks

Pierre
NB : In Google -> Web Application, I have tick Launch and deploy from 
"WebServerResources", is that correct ?
NB2 Your MainScript doesnt compile as it. 
NB3 : Application
what about      
registerRequestHandler(new wogwt.server.rpc.GWTRPCRequestHandler(), 
wogwt.server.rpc.GWTRPCRequestHandler.KEY);
if (wogwt.components.WOGWTScript.isHostedMode()) {
            setContextClassName(wogwt.GWTContext.class.getName());
}
No more needed
```

Original comment by `pierregi...@gmail.com` on 30 Aug 2011 at 7:46

Attachments:
- [GwtApp.PNG](https://storage.googleapis.com/google-code-attachments/wogwt/issue-3/comment-6/GwtApp.PNG)

**Comment by GoogleCodeExporter** [comment]
```
That's my mistake, you need to modify that argument in the VM arguments box in 
the launch configuration to change it to this:

"-DWOAINSTALLROOT=${workspace_loc:GwtExampleApp/build}"

Or if you renamed the project use the new name.
```

Original comment by `johnth...@gmail.com` on 30 Aug 2011 at 2:21

**Comment by GoogleCodeExporter** [comment]
```
Thanks, it's start now.
But sorry next problem !
When accessing the url I get error in the console : 

java.lang.ClassNotFoundException: your.app.Application
    at java.lang.ClassLoader.findClass(ClassLoader.java:358)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:251)
    at org.mortbay.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:352)
    at org.mortbay.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:337)
    at er.extensions.jspservlet.ERXServletAdaptor.invokeApplicationSetupMethod(ERXServletAdaptor.java:50)

and the amswer in the browser is :

HTTP ERROR: 404

Error initializing ERXServletAdaptor: your.app.Application

RequestURI=/GwtExampleApp/WebObjects/GwtExampleApp.woa
Caused by:

javax.servlet.UnavailableException: Error initializing ERXServletAdaptor: 
your.app.Application



Of course your.app.Application exists. Why the servlet needs it ? 
```

Original comment by `pierregi...@gmail.com` on 30 Aug 2011 at 5:26

**Comment by GoogleCodeExporter** [comment]
```
What do you have in the web.xml file?  Are the WOClasspath entries correct?  Is 
the VM arg WOAINSTALLROOT  that you changed above correct?
```

Original comment by `johnth...@gmail.com` on 30 Aug 2011 at 6:19

**Comment by GoogleCodeExporter** [comment]
```
In web.xml, I just add this as it was complaining :
<servlet>
  <servlet-name>remoteLoggingServiceImpl</servlet-name>
  <servlet-class>com.google.gwt.libideas.logging.server.RemoteLoggingServiceImpl</servlet-class>
</servlet>
<servlet-mapping>
  <servlet-name>remoteLoggingServiceImpl</servlet-name>
  <url-pattern>/your.app.gwt.Application/logging</url-pattern>
</servlet-mapping>

WOClasspath :
        <param-name>WOClasspath</param-name>
        <param-value>
            WOAINSTALLROOT/GwtExampleApp.woa/Contents/Resources/Java/your/app/Application.class
            WOAINSTALLROOT/GwtExampleApp.woa/Contents/Resources/Java
        </param-value>


in run config Arguments are :
Prog
-remoteUI "${gwt_remote_ui_server_port}:${unique_id}" -startupUrl 
http://localhost:8888/GwtExampleApp/WebObjects/GwtExampleApp.woa -logLevel INFO 
-port 8888 -war F:\Apple533\eclipse\workspace\GwtExampleApp\WebServerResources 
-codeServerPort 9998 your.app.gwt.Application
VM
-Xmx512m -Dwogwt.isHostedMode=true 
"-DWOAINSTALLROOT=${workspace_loc:GwtExampleApp/build}" -DWOIDE=WOLips

```

Original comment by `pierregi...@gmail.com` on 31 Aug 2011 at 6:38

**Comment by GoogleCodeExporter** [comment]
```
I just see that GwtExampleApp/build is not correctly generated (no jar in Java)

There is a problem with build.xml  :
Buildfile: F:\Apple533\eclipse\workspace\GwtExampleApp\build.xml
init.properties:
init.build:
compile:
[wocompile] F:\Apple533\eclipse\workspace\GwtExampleApp\build.xml:206: warning: 
'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to 
false for repeatable builds
build.woapp:
[woapplication] Installing GwtExampleApp in dist
....

As far as I can judge, the dist seems correct (image attached). 
```

Original comment by `pierregi...@gmail.com` on 31 Aug 2011 at 7:02

Attachments:
- [dist.PNG](https://storage.googleapis.com/google-code-attachments/wogwt/issue-3/comment-11/dist.PNG)

**Comment by GoogleCodeExporter** [comment]
```
If you don't have a build folder then you need to turn ON "Generate Bundles" in 
the WOLips preferences and do a clean on the workspace.
```

Original comment by `johnth...@gmail.com` on 31 Aug 2011 at 1:51

**Comment by GoogleCodeExporter** [comment]
```
This is already on.
GwtExampleApp/build is generated but 
build\GwtExampleApp.woa\Contents\Resources\Java is empty.
Is it the reason for error "ClassNotFoundException: your.app.Application"  ?

```

Original comment by `pierregi...@gmail.com` on 31 Aug 2011 at 5:04

**Comment by GoogleCodeExporter** [comment]
```
Yes
```

Original comment by `johnth...@gmail.com` on 31 Aug 2011 at 5:08

**Comment by GoogleCodeExporter** [comment]
```
wowgt seems is dependant of installation in /Library/Frameworks/. it's may be 
the origin of my problem.
Of course on my dev. Windows machine no /Library/Frameworks/ !. So I try to 
change everywhere in the framework (wogwt-build.xml and the tools) with actual 
path.
On my linux deploy machine, WO is installed in /opt
Thanks for any idea I can try. 
```

Original comment by `pierregi...@gmail.com` on 1 Sep 2011 at 11:25

**Comment by GoogleCodeExporter** [comment]
```
It uses that path only in the build.xml file and to locate the EO templates.  
On the WOGWT page under Getting Started, point 1 says: "Download WOGWT and 
install WOGWT.framework into /Library/Frameworks/. This is necessary even if 
you plan on using the WOGWT source."

What problem are having now?
```

Original comment by `johnth...@gmail.com` on 1 Sep 2011 at 2:10

**Comment by GoogleCodeExporter** [comment]
```
I started all again on linux.
The icon at the project level shows errors but nothing else inside.

I can launch but when accessing the url :
HTTP ERROR: 404

NOT_FOUND

RequestURI=/GwtExApp/WebObjects/GwtExApp.woa

Powered by Jetty:// 
```

Original comment by `pierregi...@gmail.com` on 1 Sep 2011 at 4:01

**Comment by GoogleCodeExporter** [comment]
```
Here's what you do:

1) Create a new project
2) Re-download and Install WOGWT into /Library/Frameworks (or somewhere else, 
just adjust the paths in build.xml and in the client.eogen file later)
3) Run wogwt-tool to set up the project for GWT.  Follow the instructions in 
the app.

All of this is detailed on the home page for WOGWT.

Thanks
```

Original comment by `johnth...@gmail.com` on 1 Sep 2011 at 5:27

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Thanks for your patience.


I followed your instructions. Now, I have wogwt 0.6 with gwt 2.3.
The only difference is that WO is install in /opt and Wonder/wogwt frameworks 
are in /opt/Local/Library

I change in gwt-tools  so that /Library become /opt/Local/Library
Running gwt-tools works fine. Everything is generated and the path in build.xml 
is correct.

The first problem come when I make GWT configuration :
Project has error and build gwt-compile-dev or gwt-compile doesnot generate 
anything.


I try gwt compilation :
Error "Projects using GWT 1.5 or lower may only specify one entry point module 
to compile" (?????)

I remove entry "Application" and I can compile, 
WebServerResources/you.app.gwt.Application seems then correct.


I can then launch :
>>>>>>>>>>>>>>>>
The url for GWT Development Mode connect is (probably):

http://localhost:8888/WOGWT2/WebObjects/WOGWT2.woa?gwt.codesvr=localhost:9997 

You must open a brower manually and navigate to this url.

Loading modules
   your.app.gwt.Application
      Validating <servlet> tags for module 'your.app.gwt.Application'
         [WARN] Module declares a servlet class 'com.google.gwt.libideas.logging.server.RemoteLoggingServiceImpl', but the web.xml has no corresponding declaration; please add the following lines to your web.xml:
<servlet>
  <servlet-name>remoteLoggingServiceImpl</servlet-name>
  <servlet-class>com.google.gwt.libideas.logging.server.RemoteLoggingServiceImpl</servlet-class>
</servlet>
<servlet-mapping>
  <servlet-name>remoteLoggingServiceImpl</servlet-name>
  <url-pattern>/your.app.gwt.Application/logging</url-pattern>
</servlet-mapping> 
>>>>>>>>>>>>>>>>>>>
accessing url respond :

HTTP ERROR: 404
NOT_FOUND
RequestURI=/WOGWT/WebObjects/WOGWT.woa
Powered by Jetty://

Adding remoteLoggingServiceImpl in web.xml doesnot help


Do I add to install differently WO/eclipse/WOlips to stick to /Library ?


Pierre


```

Original comment by `pierregi...@gmail.com` on 2 Sep 2011 at 10:22

**Comment by GoogleCodeExporter** [comment]
```
Dont bother reading my last comment !
I fix entry-point Application with the one in GwtExampleApp.zip and it works.

Thanks a lot
```

Original comment by `pierregi...@gmail.com` on 2 Sep 2011 at 1:02
